"""FIPS-aware country code -> display name.

GDELT (our dominant source) emits FIPS 10-4 country codes, which collide with
ISO 3166-1 on many values (FIPS RS=Russia vs ISO RS=Serbia; FIPS IS=Israel vs
ISO IS=Iceland). This table is generated from the frontend's hybrid map
(worldview/src/globe/countries.ts) — FIPS meaning wins on collisions,
non-colliding ISO codes are included for non-GDELT sources. Regenerate by
copying that file's COUNTRY_NAMES if it changes.
"""

from __future__ import annotations

REGION_NAMES: dict[str, str] = {
    "US": "United States",
    "CA": "Canada",
    "MX": "Mexico",
    "BR": "Brazil",
    "AR": "Argentina",
    "CI": "Chile",
    "CL": "Chile",
    "CO": "Colombia",
    "PE": "Peru",
    "VE": "Venezuela",
    "CU": "Cuba",
    "HA": "Haiti",
    "HT": "Haiti",
    "DR": "Dominican Republic",
    "JM": "Jamaica",
    "GT": "Guatemala",
    "HO": "Honduras",
    "HN": "Honduras",
    "NU": "Nicaragua",
    "PM": "Panama",
    "CS": "Costa Rica",
    "CR": "Costa Rica",
    "EC": "Ecuador",
    "BL": "Bolivia",
    "UY": "Uruguay",
    "PA": "Paraguay",
    "PY": "Paraguay",
    "GY": "Guyana",
    "SR": "Suriname",
    "BB": "Barbados",
    "TD": "Trinidad and Tobago",
    "TT": "Trinidad and Tobago",
    "BF": "Bahamas",
    "BS": "Bahamas",
    "GJ": "Grenada",
    "UK": "United Kingdom",
    "GB": "United Kingdom",
    "EI": "Ireland",
    "IE": "Ireland",
    "FR": "France",
    "GM": "Germany",
    "DE": "Germany",
    "IT": "Italy",
    "SP": "Spain",
    "ES": "El Salvador",
    "PO": "Portugal",
    "PT": "Portugal",
    "NL": "Netherlands",
    "BE": "Belgium",
    "SZ": "Switzerland",
    "AU": "Austria",
    "AT": "Austria",
    "SW": "Sweden",
    "SE": "Sweden",
    "NO": "Norway",
    "DA": "Denmark",
    "DK": "Denmark",
    "FI": "Finland",
    "IC": "Iceland",
    "PL": "Poland",
    "EZ": "Czech Republic",
    "CZ": "Czech Republic",
    "HU": "Hungary",
    "RO": "Romania",
    "GR": "Greece",
    "RB": "Serbia",
    "HR": "Croatia",
    "AL": "Albania",
    "MJ": "Montenegro",
    "MK": "North Macedonia",
    "SI": "Slovenia",
    "LO": "Slovakia",
    "SK": "Slovakia",
    "UP": "Ukraine",
    "UA": "Ukraine",
    "BO": "Belarus",
    "RS": "Russia",
    "RU": "Russia",
    "TU": "Turkey",
    "TR": "Turkey",
    "LU": "Luxembourg",
    "MT": "Malta",
    "AN": "Andorra",
    "GI": "Gibraltar",
    "MD": "Moldova",
    "IS": "Israel",
    "IL": "Israel",
    "LE": "Lebanon",
    "LB": "Lebanon",
    "SY": "Syria",
    "JO": "Jordan",
    "IZ": "Iraq",
    "IQ": "Iraq",
    "IR": "Iran",
    "SA": "Saudi Arabia",
    "AE": "United Arab Emirates",
    "TC": "United Arab Emirates",
    "QA": "Qatar",
    "KU": "Kuwait",
    "KW": "Kuwait",
    "YM": "Yemen",
    "YE": "Yemen",
    "BA": "Bahrain",
    "BH": "Bahrain",
    "MU": "Oman",
    "OM": "Oman",
    "EG": "Egypt",
    "LY": "Libya",
    "TS": "Tunisia",
    "AG": "Algeria",
    "DZ": "Algeria",
    "MO": "Morocco",
    "MA": "Madagascar",
    "SU": "Sudan",
    "SD": "Sudan",
    "SO": "Somalia",
    "ET": "Ethiopia",
    "KE": "Kenya",
    "UG": "Uganda",
    "TZ": "Tanzania",
    "RW": "Rwanda",
    "BY": "Burundi",
    "NI": "Nigeria",
    "NG": "Niger",
    "NE": "Niger",
    "GH": "Ghana",
    "IV": "Côte d'Ivoire",
    "ML": "Mali",
    "SG": "Senegal",
    "CM": "Cameroon",
    "CG": "Republic of the Congo",
    "CF": "Central African Republic",
    "CD": "DR Congo",
    "SF": "South Africa",
    "ZA": "South Africa",
    "ZI": "Zimbabwe",
    "ZW": "Zimbabwe",
    "AO": "Angola",
    "MZ": "Mozambique",
    "WA": "Namibia",
    "TO": "Togo",
    "EK": "Equatorial Guinea",
    "GA": "Gambia",
    "GV": "Guinea",
    "PU": "Guinea-Bissau",
    "IN": "India",
    "PK": "Pakistan",
    "BG": "Bangladesh",
    "BD": "Bangladesh",
    "BU": "Bulgaria",
    "CE": "Sri Lanka",
    "LK": "Sri Lanka",
    "NP": "Nepal",
    "AF": "Afghanistan",
    "BT": "Bhutan",
    "MV": "Maldives",
    "JA": "Japan",
    "JP": "Japan",
    "KS": "South Korea",
    "KR": "South Korea",
    "KN": "North Korea",
    "KP": "North Korea",
    "CH": "China",
    "CN": "China",
    "TW": "Taiwan",
    "HK": "Hong Kong",
    "MC": "Macau",
    "VM": "Vietnam",
    "VN": "Vietnam",
    "TH": "Thailand",
    "LA": "Laos",
    "CB": "Cambodia",
    "KH": "Cambodia",
    "BM": "Myanmar",
    "MM": "Myanmar",
    "MY": "Malaysia",
    "ID": "Indonesia",
    "RP": "Philippines",
    "PH": "Philippines",
    "SN": "Singapore",
    "MG": "Mongolia",
    "MN": "Mongolia",
    "KZ": "Kazakhstan",
    "UZ": "Uzbekistan",
    "KG": "Kyrgyzstan",
    "TI": "Tajikistan",
    "TJ": "Tajikistan",
    "TX": "Turkmenistan",
    "TM": "Turkmenistan",
    "AJ": "Azerbaijan",
    "AZ": "Azerbaijan",
    "AM": "Armenia",
    "GG": "Georgia",
    "GE": "Georgia",
    "AS": "Australia",
    "NZ": "New Zealand",
    "PP": "Papua New Guinea",
    "PG": "Papua New Guinea",
    "FJ": "Fiji",
    "NH": "Vanuatu",
    "VU": "Vanuatu",
    "WS": "Samoa",
}


def region_name(code: str | None) -> str | None:
    """Code -> display name, or None so callers omit a bare code."""
    if not code:
        return None
    return REGION_NAMES.get(code.strip().upper())
